name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.15'
          allow-prereleases: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ clang valgrind

      - name: Build nob
        run: cc -x c -o nob nob.h

      - name: Run build and tests
        run: ./nob
        env:
          SNAKEPATH_SANITIZE: "1"

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.15'
          allow-prereleases: true

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build nob
        run: cl.exe /Fe:nob.exe /Tcnob.h

      - name: Run build and tests
        run: .\nob.exe
